export enum Currency {
  USD = 'USD',
  EUR = 'EUR',
  UAH = 'UAH',
}

export enum Region {
  VINNYTSIA = 'Vinnytsia',
  VOLYN = 'Volyn',
  DNIPROPETROVSK = 'Dnipropetrovsk',
  DONETSK = 'Donetsk',
  ZHYTOMYR = 'Zhytomyr',
  ZAKARPATTIA = 'Zakarpattia',
  ZAPORIZHIA = 'Zaporizhia',
  IVANO_FRANKIVSK = 'Ivano-Frankivsk',
  KYIV = 'Kyiv',
  KIROVOHRAD = 'Kirovohrad',
  LUHANSK = 'Luhansk',
  LVIV = 'Lviv',
  MYKOLAIV = 'Mykolaiv',
  ODESA = 'Odesa',
  POLTAVA = 'Poltava',
  RIVNE = 'Rivne',
  SUMY = 'Sumy',
  TERNOPIL = 'Ternopil',
  KHARKIV = 'Kharkiv',
  KHERSON = 'Kherson',
  KHMELNYTSKYI = 'Khmelnytskyi',
  CHERKASY = 'Cherkasy',
  CHERNIVTSI = 'Chernivtsi',
  CHERNIHIV = 'Chernihiv',
  REPUBLIC_OF_CRIMEA = 'Republic of Crimea',
}
